version: '3.9'
services:
  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      #- ./backend/.env
      - ./backend/.env.local
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    restart: unless-stopped
    env_file:
      #- ./frontend/.env
      - ./frontend/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - backend
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: statuswise
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
